config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index new update create show edit destroy] do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy # dependent, quando o rest é destruido, a review tbm sera
  validates :name, :address, presence: true, uniqueness: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

#  validates :rating, inclusion: { in: [0,1,2,3], allow_nil: false } ???

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show update edit destroy]

  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
    @review = Review.new
  end

  # def chef
  # end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
       # indica para renderizar a view "new" e usar o status
       # "unprocessable_entity" que representa um erro no processamento
       # de uma requisição.
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
  end

   private
    # serve para refatorar um codigo utilizado varias vezes no
    # before_action

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'reviews/new', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy

    redirect_to restaurant_path(@restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number%>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class='container'>
  <h1>Editing restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "Show this restaurant", @restaurant %> |
    <%= link_to "Back to restaurants", restaurants_path %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class='container'>
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <p><%= restaurant.name %><br>
      <%= link_to "Detalhes", restaurant_path(restaurant), class: "btn-sm btn-primary"%>
  <% end %>
</div>

<%= link_to "Criar restaurante", new_restaurant_path, class: "btn btn-success"%>
</div>

app/views/restaurants/new.html.erb
<div class='container'>
  <h1>Novo restaurante:</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "Back to restaurants", restaurants_path%>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class='container'>
 <p style="color: green"><%= notice %></p>


 <h4><%= @restaurant.name %></h4>


 <div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>
  <br>
 <br><%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
 </div>

 <br>
 <h2>Reviews:</h2>

 <ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %>
      <%= link_to "remove", review_path(review), data: { turbo_method: :delete }, class: 'btn-sm btn-danger' %>
    </li>
  <% end %>
 </ul>

 <h2>Comente sobre o restaurante!</h2>

  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Comentar!", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/reviews/new.html.erb
 <h2>Comente sobre o restaurante!</h2>

  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Comentar!", class: 'btn btn-primary' %>
  <% end %>
</div>